### ISSUE TITLE
从商品详情进入购物车会报错

### ISSUE THREAD

**Issue by sleepyyj** [heyushuo/mpvue-shop#18]
`thirdScriptError
Cannot read property '__wxWebviewId__' of null;at "pages/categorylist/main" page lifeCycleMethod onUnload function
TypeError: Cannot read property '__wxWebviewId__' of 'null'
    at Vue$3.pageId [as $pageId] (http://127.0.0.1:25720/appservice/static/js/app.js:207:47)
    at Vue$3.onUnload (http://127.0.0.1:25720/appservice/static/js/app.js:231:35)
    at callHook$1 (http://127.0.0.1:25720/appservice/static/js/vendor.js:4713:33)
    at r.onUnload (http://127.0.0.1:25720/appservice/static/js/vendor.js:5030:15)
    at r.<anonymous> (http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:24831)
    at R (http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:1550)
    at U (http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:2516)
    at K (http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:3414)
    at Function.<anonymous> (http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:6274)
    at http://127.0.0.1:25720/appservice/__dev__/WAService.js:18:12486`

从商品详情进入购物车会报这个错误
从tabBar进入购物车不会报错

**Comment by weijing24** [comment]
why author haven't answer you？You should reflect on yourself. @sleepyyj
